name: vertical_sliding_drawers
description: "Flutter plugin for create vertical sliding drawers and manage them"
version: 0.8.1
repository: https://github.com/orcunoz/sliding_drawers

environment:
  sdk: ">=3.3.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.18.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
